### PR TITLE
Working on a md->pdf process

### PR DESCRIPTION
**Pull request by temas**
This is a WIP branch to track a full md->pdf process.

Currently I'm testing it using the node script -> [prince](http://www.princexml.com) with HTMLBook default css

### CODE REVIEW

**Comment by dvanduzer** [comment]
Why prince over pandoc?

**Comment by temas** [comment]
Largely because latex makes me puke?  After playing with a lot of tools to publish a book, prince stood out, a lot.  Until I can find time to write my own ;)

**Comment by temas** [comment]
To be clear we're not bound to any technology, HTML + CSS --> PDF is the process

**Comment by quartzjer** [comment]
@temas could you add the command to build the pdf to the package.json too?

anything else before you think this is mergeable to work from master?

**Comment by stpeter** [comment]
Why are we building our own documentation toolchain? ;-)

**Comment by temas** [comment]
I merely wrote a md -> htmlbook tool, and then we use normal tools ;)

**Pull request merged**
